### ISSUE TITLE
Error in the reporting the result in the trial list

### ISSUE THREAD

**Issue by alessli** [Gavin-Perry/OdorChoice#32]
In a trial 3 -2 A on the left, i picked the right side (-2), and the result reported was 'A4R'. Similarly, trial -5 1 L, licked left, received 5 drops but result was B0L.

**Comment by Gavin-Perry** [comment]
Fixed in V29 please retest

**Comment by alessli** [comment]
Not fixed, please reopen.
I input a list with: 
1 3 -2.
First trial was 3 -2 R, I licked on the right side, and obtained this
![issue32](https://github.com/user-attachments/assets/8312c35a-7109-4f7e-8986-84c3955b1ed4)
![issue32_mlapp](https://github.com/user-attachments/assets/b076e182-1c29-4234-ae05-8bec05b20df2)

**Comment by alessli** [comment]
However, on the following iterations everything worked as expected.

**Comment by Gavin-Perry** [comment]
That's what I get for only testing AA and BB recently. for AB trials Pico was rewarding either side!
All fixed in v35

**Comment by Gavin-Perry** [comment]
I misunderstood (brain fart) and v35 is wrong!
v34 (unreleased) doesn't have that error but it gave double rewards on 2 AB trials
1	5	L	A1L
  L   437011
  L   437352
  L   437669
  A   437352
#End CWT 439736  1
  A   438544
  Z   440746

2	3	L	A2L
  L   492267
  L   492513
  L   492801
  L   493073
  A   491988
  L   493927
  L   494198
#End CWT 494373  1
  A   493181
  L   494467

Working on it..... Don't use 35 if you downloaded it already

**Comment by Gavin-Perry** [comment]
Missing a break in switch.
Now version 36 for both ML and Pico
