### ISSUE TITLE
Code should wait for the error of sound duration

### ISSUE THREAD

**Issue by alessli** [Gavin-Perry/OdorChoice#36]
In case of an F response, code has to wait for the end of error sound before moving to the next trial.

**Comment by Gavin-Perry** [comment]
I think this has always been true. 
With v29 please check and reopen issue if there is still a problem

**Comment by alessli** [comment]
V29, with ino 28 is not fixed. On the second trial, it went on a no exit while loop where the buzz kept playing until i killed matlab

**Comment by Gavin-Perry** [comment]
Fixed in v30

**Comment by alessli** [comment]
Not fixed. with v30, If I increase duration of the error sound, code goes on a never ending loop that plays the sound until i reset pico and kill matlab. Please reopen  the issue.

**Comment by Gavin-Perry** [comment]
I haven't seen that. What was the trial condition and how long did you set for the error buzz?

**Comment by alessli** [comment]
The error is easily reproducible in any  trial where the is a possible F story. In my hands, any error sound time different than 0.5 generates the bug.

**Comment by Gavin-Perry** [comment]
Converted from sec to msec (*1000) in 2 places, made for a very long buzz indeed.
Fixed in 31
